In [1]:
import cv2
import sys
import os
import time
import random
import numpy as np
import tensorflow as tf

## 回调函数

In [ ]:
def CannyThreshold(lowThreshold):
    detected_edges = cv2.Canny(detected_edges,
                               lowThreshold,
                               lowThreshold*ratio,
                               apertureSize = kernel_size)
    dst = cv2.bitwise_and(img,img,mask = detected_edges)  # just add some colours to edges from original image.
    cv2.imshow('canny demo',dst)

In [ ]:
SIZE = 1280
WIDTH = 32
HEIGHT = 32
NUM_CLASSES = 34
iterations = 1000
# 测试图片名
# 2_120811_aa81fa193f7e8b2.jpg
dir = "E:/SegCard/sample/"
filename = "2_120811_aa81fa193f7e8b2.jpg"
src = cv2.imread(dir+filename)

resize = cv2.resize(src,(600,400))
gray = cv2.cvtColor(resize,cv2.COLOR_BGR2GRAY)
cv2.equalizeHist(gray,gray)
gaus = cv2.GaussianBlur(gray,(11,11),0)
edges = cv2.Canny(gaus, 50, 150, apertureSize=3)

# lines = cv2.HoughLinesP(edges,1,np.pi/180,160)
# for line in lines:
#     for x1, y1, x2, y2 in line:
#         cv2.line(resize, (x1, y1), (x2, y2), (0, 255, 0), 2)
lines = cv2.HoughLines(edges, 0.8, np.pi / 180, 80, 0, 0)
# 3.将检测的线画出来（注意是极坐标噢）
print(lines)
for line in lines:
    rho, theta = line[0]
    a = np.cos(theta)
    b = np.sin(theta)
    x0 = a * rho
    y0 = b * rho
    x1 = int(x0 + 1000 * (-b))
    y1 = int(y0 + 1000 * (a))
    x2 = int(x0 - 1000 * (-b))
    y2 = int(y0 - 1000 * (a))
    cv2.line(resize, (x1, y1), (x2, y2), (0, 0, 255))

cv2.imshow("houghline",resize)
cv2.imshow("edges",edges)
cv2.waitKey(0)

[[[  9.04000015e+01   1.58824956e+00]]

 [[  2.80800018e+02   1.57079637e+00]]

 [[  1.48800003e+02   1.57079637e+00]]

 [[  1.32000000e+02   1.57079637e+00]]

 [[  6.95999985e+01   8.72664601e-02]]

 [[  1.43199997e+02   1.57079637e+00]]]
